// generated by: rails generate ar_sync:types client/src/typed/

import { TypeRequest, ApiNameRequests } from './types'
import { DataTypeFromRequest } from 'ar_sync/core/DataType'
import ArSyncModelBase from 'ar_sync/graph/ArSyncModel'
export default class ArSyncModel<R extends TypeRequest> extends ArSyncModelBase<{}> {
  constructor(r: R) { super(r) }
  data: DataTypeFromRequest<ApiNameRequests[R['api']], R> | null
}
